# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: moebiussolutions/cac-agent.docker.circleci
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

# Disabled caching. "dependency:go-offline" doesn't seem to work
# with dependencies between modules being built.
#
#      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v2-dependencies-{{ checksum "pom.xml" }}
#          # fallback to using the latest cache if no exact match is found
#          - v2-dependencies-
#
#      - run: mvn dependency:go-offline
#
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: v2-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - run: mvn -P circleci integration-test -DJDK_8_HOME="$JDK_8_HOME" -DJDK_11_HOME="$JDK_11_HOME"


      - store_artifacts:
          path: ~/repo/cac-jgit/target/cac-jgit.jar
          destination: cac-jgit.jar
      - store_artifacts:
          path: ~/repo/cac-ssl-relay/target/cac-ssl-relay.jar
          destination: cac-ssl-relay.jar
